# Generated by Django 3.1.5 on 2021-02-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/host/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(default='20500', max_length=10)),
                ('state', models.CharField(max_length=3)),
                ('host_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.host')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSizesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('min_width', models.FloatField()),
                ('min_length', models.FloatField()),
            ],
            options={
                'verbose_name': 'Parking Space Size',
                'verbose_name_plural': 'Parking Space Sizes',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=1)),
                ('actual_width', models.FloatField(default=9.0)),
                ('actual_length', models.FloatField(default=18.0)),
                ('price', models.FloatField(default=5.0)),
                ('notes', models.CharField(default='', max_length=100)),
                ('location_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.location')),
                ('parking_size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.parkingsizestable', verbose_name='Parking Size')),
            ],
            options={
                'verbose_name_plural': 'Parking Spots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=100)),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/users/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2015)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('license', models.CharField(max_length=8)),
                ('description', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('host_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hash_str', models.CharField(max_length=100)),
                ('host_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.host')),
                ('location_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.location')),
                ('spot_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.parkingspot')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.user')),
                ('vehicle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/location/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_api.location')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/attendant/')),
                ('host_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking_api.host', verbose_name="Host's ID")),
            ],
        ),
    ]
