# Generated by Django 3.1.5 on 2021-04-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='boss',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_api.host'),
        ),
    ]
