# Generated by Django 3.1.5 on 2021-01-29 01:21


"""
After running:
$ python manage.py makemigrations parking
$ python manage.py sqlmigrate parking 0001
$ python manage.py migrate

$ run python manage.py makemigration --empty parking --name populate

This will make a file called 0002_populate.py in src/RubberDuckyParking/parking/migrations

Replace the contents of 0002_populate.py with this file.

Then run:

$ python manage.py makemigrations
$ python manage.py migrate

You now have prepopulated data for the app.
"""
from django.db import migrations


def populate_db(apps, schema_editor):
    # getting links to the tables
    parking_table = apps.get_model('parking', 'ParkingTable')
    user_table = apps.get_model('parking', 'User')
    host_table = apps.get_model('parking', 'Host')
    location_table = apps.get_model('parking', 'Location')
    transaction_table = apps.get_model('parking', 'Transactions')
    image_table = apps.get_model('parking', 'Image')

    standard_spot = parking_table(name="Standard Spot", description="A standard parking spot that you'd find at a grocery store or mall.", min_width=9.0, min_length=18.0)
    standard_spot.save()
    compact_spot = parking_table(name="Compact Spot", description="A compact parking spot for smaller sized cars", min_width=8.0, min_length=16)
    compact_spot.save()
    large_spot = parking_table(name="Extra length Spot", description="A longer parking spot that is the equivalent of 2 standard spots stacked end to end", min_width=9.0, min_length=36.0)
    large_spot.save()
    tailgate_spot = parking_table(name="Tailgate Spot", description="The best spot for a tailgaters paradise. Has all the space for grills, RVs and chairs.", min_width=15.0, min_length=36.0)
    tailgate_spot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
